### ISSUE TITLE
Reading Data from Readable Stream

### ISSUE THREAD

**Issue by michaeldera** [michaeldera/image-accessibility-extension#2]
**Describe the bug**
When I call the REST endpoint that is supposed to receive the JSON payload with the content of the image, I get a Readable Stream object in the response body (`response.body`), I am not having the best time trying to read the stream. 

**To Reproduce**
1. Clone the repo and and set up the extension in developer mode as inidcated in the [contributing guidelines](https://github.com/michaeldera/image-accessibility-extension/blob/master/CONTRIBUTING.md)
2. Active the extension and add a debugger (`debugger;`) on the response from `fetch`;
4. Inspection of the `response.body` after reloading a page with an image without alt atttributes will indicate it is a readable stream

**Expected behavior**
Would like to either be able to read the stream or to receive the response as a JSON payload (Worth mentioning that tools such as Swagger, Insomnia, Postman receive the reponse as JSON)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Microsoft Edge (Chromium)
 - Version 81.0.416.68 (Official build) (64-bit)

**Comment by teddychief** [comment]
Respect bro

**Comment by michaeldera** [comment]
Thank you.
